name: AnnotaFlow
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - cmake
  - pip
  - qt-main
  - numpy
  - pillow
  - opencv
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - pip:
      - git+https://github.com/facebookresearch/sam2.git
